name: Main Branch Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  ci-step:
    uses: raghudevopsb81/github-reusable-actions/.github/workflows/ci-main.yaml@main
    with:
      componentName: user
      SONAR_CLASS_PATH: " "
    secrets:
      NR_API_KEY: ${{ secrets.NR_API_KEY }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
